#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

"$DIR/prestart/CMD-R" "$DIR" "Updating Ultimate Commander..." &
CMD_R_PID=$!
"$DIR/update"
echo 1 > "$DIR/exitprestart"
while [ -d /proc/$CMD_R_PID ]
do
    sleep 1
done
rm "$DIR/exitprestart"
"$DIR/cmd-r" $@
