#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIROLD=$(pwd)
cd "$DIR"

echo Cloning git repo...
git clone -q https://github.com/SkySwimmer/UltimateCommander.git Update
if [ -d "Update" ]; then
    cd Update
    echo Compiling...
    chmod +x ./configure
    ./configure
    ./applypatches.sh
    make
    echo Installing...
    cp work/build/* .. -r -f
    cd ..
    echo Removing repo folder...
    rm -r Update -f
    echo Finished.
else
    echo Cloning failed.
fi

cd "$DIROLD"
